# Copyright (c) 2024, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.
resolution-mode: benders-decomposition
models:
  - id: lib_example_13_2_add_on.continuous_invest_add_on
    model-decomposition:
      variables:
        - id: p_max
          location: master-and-subproblems

      objective-contributions:
        - id: invest_objective
          location: master
  
  - id: lib_example_13_2_add_on.discrete_invest_add_on
    model-decomposition:
      variables:
        - id: p_max
          location: master-and-subproblems
        - id: invested_units
          location: master-and-subproblems
      constraints:
        - id: units_capa_relationship
          location: master

      objective-contributions:
        - id: invest_objective
          location: master
