# Copyright (c) 2024, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.
models:
  - id: lib_example_13_1.continuous_invest_add_on
    model-decomposition:
      variables:
        - id: p_max
          location: master-and-subproblems

        # Variable generation has default settings, no need to make it appear here
      objective-contributions:
        - id: invest_objective
          location: master
